#!/bin/bash
###############################################################################
# Installs everything onto a WSL Ubuntu 22.04.
#
# Usage:
# 1. Log into a freshly installed WSL Ubuntu 22.04.
# 2. If logged in as non-root, switch to root with `sudo su`
# 3. Execute the following commands: 
#
#    cd tmp
#    git clone https://github.com/sandor-juhasz/installers.git
#    cd installers/src
#    host-os-installers/wsl-ubuntu-installer
#
###############################################################################

set -e 

export DEFAULT_USERNAME=developer

source lib/common.sh

echo "Setting up WSL Ubuntu..."

apt-get update
apt-get -y upgrade

installers/default-user.sh developer
installers/zsh.sh developer
installers/shell-base.sh developer

#
# Installing an extensible Python environment with System Python.
#
export USERNAME=$DEFAULT_USERNAME
installers/pyenv.sh
installers/python.sh developer system
installers/pipx.sh developer

# installers/docker.sh    # No additional steps are needed. Enable the distro in the Docker Engine settings.
installers/vscode.sh

#
# Git settings
#
installers/gh.sh
installers/git-credential-manager.sh developer


installers/devpm.sh developer
installers/dotfiles.sh developer
