#!/bin/bash
###############################################################################
# Installs everything needed to work with development containers on a 
# WSL Ubuntu 22.04 VM.
#
# Parameters    
#     --default-username=username   Default: "developer"
#     --default-password=password   Default: "welcome"
#     --install-docker-engine       Default: "false" 
#     --install-dotfiles            Default: "false"
#     --install-zsh                 Default: "false"
#
# Usage:
# 1. Log into a freshly installed WSL Ubuntu 22.04.
# 2. If logged in as non-root, switch to root with `sudo su`
# 3. Execute the following commands: 
#
#    cd tmp
#    git clone https://github.com/sandor-juhasz/installers.git
#    cd installers/src
#    host-os-installers/wsl-ubuntu-installer    # Add additional parameters
#
###############################################################################

set -e 

source lib/common.sh

DEFAULT_USERNAME=developer
DEFAULT_PASSWORD=welcome
INSTALL_DOCKER_ENGINE=false
INSTALL_DOTFILES=false
INSTALL_ZSH=false
for i in "$@"; do
  case $i in
    --install-zsh)
      INSTALL_ZSH=true
      shift # past argument=value
      ;;
    --install-dotfiles)
      INSTALL_DOTFILES=true
      shift # past argument=value
      ;;
    --install-docker-engine)
      INSTALL_DOCKER_ENGINE=true
      shift # past argument=value
      ;;
    --default-username=*)
      DEFAULT_USERNAME="${i#*=}"
      shift # past argument=value
      ;;
    --default-password=*)
      DEFAULT_PASSWORD="${i#*=}"
      shift # past argument=value
      ;;
    -*)
      echo "Unknown option $i"
      exit 1
      ;;
    *)
      ;;
  esac
done

export DEFAULT_USERNAME=$DEFAULT_USERNAME

echo "Setting up WSL Ubuntu..."
echo "   Default username:      $DEFAULT_USERNAME"
echo "   Default password:      $DEFAULT_PASSWORD"
echo "   Install Docker Engine: $INSTALL_DOCKER_ENGINE"
echo "   Install Dotfiles:      $INSTALL_DOTFILES"
echo "   Install ZSH:           $INSTALL_ZSH"

apt-get update
apt-get -y upgrade

installers/default-user.sh "${DEFAULT_USERNAME}"
if [[ "$INSTALL_ZSH" == true ]]; then
    installers/zsh.sh "${DEFAULT_USERNAME}"
fi
installers/shell-base.sh "${DEFAULT_USERNAME}"

#
# Installing an extensible Python environment with System Python.
#
export USERNAME=$DEFAULT_USERNAME
installers/pyenv.sh
installers/python.sh "${DEFAULT_USERNAME}" system
installers/pipx.sh "${DEFAULT_USERNAME}"

#
# Docker, DevContainer and VSCode installation
#
if [[ "$INSTALL_DOCKER_ENGINE" == true ]]; then
    installers/docker-engine.sh "${DEFAULT_USERNAME}"
fi
installers/vscode.sh
installers/nvm.sh "${DEFAULT_USERNAME}"
installers/node.sh "${DEFAULT_USERNAME}"
installers/devcontainer-cli.sh "${DEFAULT_USERNAME}"

#
# Git settings
#
installers/gh.sh
installers/git-credential-manager.sh "${DEFAULT_USERNAME}"

#
# Own customizations
#
if [[ "$INSTALL_DOTFILES" == true ]]; then
    installers/devpm.sh "${DEFAULT_USERNAME}"
    installers/dotfiles.sh "${DEFAULT_USERNAME}"
fi
